spring.application.name=api
server.port=8080
spring.profiles.active=h2

game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

game.taquin.default-player-count=1
game.taquin.default-board-size=4

game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

users.services.url=http://localhost:8081

jwt.secret=${JWT_SECRET:3c4f0126772e0cba85e9d3a268adb9978ab9d7d6b6c5aecdd308aa1acffae2e0}