# Configuration Base de données H2 (fichier persistant permettant de survivre au redémarrage)
spring.datasource.url=jdbc:h2:file:./data/gamesdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Initialisation SQL pour le mode JDBC
spring.sql.init.mode=always

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
